config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/home'
  root 'welcome#home'

  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  get 'books/list', to: 'books#list', as: 'list_books'
  get 'book/detail/:id', to: 'books#detail', as: 'detail_book'
  resources :books do
    resources :reviews, only: [ :new, :create, :index, :show ]
    #get 'reviews', to: 'reviews#show', as: 'review'
    #get 'reviews/new', to: 'reviews#new'
    #post 'reviews', to: 'reviews#show'
  end
  
  #map.resources :books, has_many: :reviews
  
  resources :reviews, only: :destroy
  
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'user_edit'
  delete '/users/:id', to: 'users#destroy'
  patch '/users/:id', to: 'users#updateinfo'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  # Removed the following default modules: :trackable
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :validatable, :omniauthable
  has_many :reviews
  has_many :books, through: :reviews
  has_one :user_info
  accepts_nested_attributes_for :user_info
  before_create :skip_confirmation!
  
  def self.find_for_oauth(auth, signed_in_resource = nil)

    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end
    
    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end
  
  def skip_confirmation!
    self.confirmed_at = Time.now
  end
  
  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
  
  def set_info=(user_info)
    info = UserInfo.find_or_create_by(user_id: self.id)
    info.update(user_info)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :updateinfo, :finish_signup, :destroy]

  def show
    if @user.admin?
      @books = Book.all
      @users = User.all
      @reviews = Review.all
      render 'admin'
    end
  end

  def edit
  end
  
  def updateinfo
    @user.set_info = params[:user].require(:info).permit(:name, :city, :state)
    redirect_to user_path(current_user)
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => false)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_signup
    # authorize! :update, @user
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        #@user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:email)
    end

    def info_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
    
end

app/views/users/admin.html.erb
<h3>Books</h3>
<% if !@books.empty? %>
  <table border="1">
    <thead>
      <td>ID</td>
      <td>Title</td>
      <td>Author</td>
      <td>Year</td>
      <td>Fiction?</td>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
        <td><%= book.id %></td>
        <td><%= link_to(book.title, book_path(book.id)) %></td>
        <td><%= book.author %></td>
        <td><%= book.year %></td>
        <% if book.fiction %>
          <td>Fiction</td>
        <% else %>
          <td>Non-Fiction</td>
        <% end %>
        <td><%= link_to("Edit Book", edit_book_path(book.id)) %></td>
        <td><%= link_to("Delete Book", book, method: :delete ) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<h3>Users</h3>
<table border="1">
  <thead>
    <td>ID</td>
    <td>User</td>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= link_to("Delete User", user, method: :delete) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Reviews</h3>
<% if !@reviews.empty? %>
  <table border="1">
    <thead>
      <td>Book</td>
      <td>User</td>
      <td>Summary</td>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
        <td><%= review.book_id %></td>
        <td><%= review.user_id %></td>
        <td><%= review.summary %></td>
        <td><%= link_to("Delete Review", review, method: :delete ) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/edit.html.erb
<% userinfo = UserInfo.find_by(user_id: @user.id) %>
<%= form_for @user do |f| %>
  <%= f.fields_for :info do |i| %>
    <% if userinfo.nil? %>
      <div id="user-info">
      <%= i.label :name %>
      <%= i.text_field :name %><br>
      </div>
      <div id="user-info">
      <%= i.label :city %>
      <%= i.text_field :city %><br>
      </div>
      <div id="user-info">
      <%= i.label :state %>
      <%= i.text_field :state %><br>
      </div>
    <% else %>
      <div id="user-info">
      <%= i.label :name %>
      <%= i.text_field :name, value: userinfo.name %><br>
      </div>
      <div id="user-info">
      <%= i.label :city %>
      <%= i.text_field :city, value: userinfo.city%><br>
      </div>
      <div id="user-info">
      <%= i.label :state %>
      <%= i.text_field :state, value: userinfo.state %><br>
      </div>
    <% end %>
      <div id="user-info">
    <%= f.submit %>
      </div>
  <% end %>
<% end %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% if @user.user_info.nil? || @user.user_info.name.nil? %>
  <h3>Welcome, User</h3>
<% else %>
  <h3>Welcome, <%= @user.user_info.name %></h3>
<% end %>
<% if !Review.user_review(current_user).empty? %>
  <p>Your Reviews</p>
  <table border='1'>
    <tr>
      <th>Title</th>
      <th>Rating</th>
      <th>Body</th>
    </tr>
    <% Review.user_review(current_user).each do |review| %>
    <tr>
      <td><%= review.book.title %></td>
      <td><%= review.rating %></td>
      <td><%= review.summary %></td>
      <td><%= review.body %></td>
    <% end %>
    </tr>
  </table>
<% else %>
  <h3>You have not reviewed any books!</h3>
<% end %>
<div class="links">
  <%= link_to("My personal information", user_edit_path(current_user.id)) %>
</div>