config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/home'
  root 'welcome#home'

  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  get 'books/list', to: 'books#list', as: 'list_books'
  get 'book/detail/:id', to: 'books#detail', as: 'detail_book'
  resources :books do
    resources :reviews, only: [ :new, :create, :index, :show ]
    #get 'reviews', to: 'reviews#show', as: 'review'
    #get 'reviews/new', to: 'reviews#new'
    #post 'reviews', to: 'reviews#show'
  end
  
  #map.resources :books, has_many: :reviews
  
  resources :reviews, only: :destroy
  
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'user_edit'
  delete '/users/:id', to: 'users#destroy'
  patch '/users/:id', to: 'users#updateinfo'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :title, :author, :year, presence: true
end

app/controllers/books_controller.rb
require 'pry'
class BooksController < ApplicationController
  before_action :load_book, only: [:show, :edit, :update, :destroy]
  
  def index
    #@books = Book.all
  end
  
  def show
    @isReviewed = !(current_user.reviews.select {|review| review["book_id"] == @book.id}).empty?
  end
  
  def edit
  end
  
  def create
    @book = Book.new(params.require(:book).permit(:title, :author, :year, :fiction))
    if @book.save
      redirect_to book_path(@book)
    else
      flash[:error] = "Please fill in all fields"
      render :new
    end
  end
  
  def new
    @book = Book.new
  end
  
  def update
    @book.assign_attributes(params.require(:book).permit(:title, :author, :year, :fiction))
    if @book.valid?
      @book.update(params.require(:book).permit(:title, :author, :year, :year, :fiction))
      redirect_to book_path(@book)
    else
      flash[:error] = "All fields must be specified"
      render :edit
    end
  end
  
  def destroy
    if !@book.nil?
      @book.destroy
    end
    redirect_to books_path
  end
  
  def list
    @books = Book.all
    render json: @books
  end
  
  def detail
    #binding.pry
    @book = Book.find_by(id: params[:id])
    render json: @book
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= form_for(@book) do |book| %>
  <%= book.label :title %>
  <%= book.text_field :title %><br>
  <%= book.label :author %>
  <%= book.text_field :author %><br>
  <%= book.label :year %>
  <%= book.number_field :year %><br>
  <%= book.label :fiction %>
  <%= book.check_box :fiction %><br>
  <%= book.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'book' %>

app/views/books/index.html.erb
<h1>Reviewed Books</h1>
  <table border="1">
    <thead>
      <td>Title</td>
      <td>Author</td>
      <td>Year</td>
      <td>Fiction?</td>
    </thead>
    <tbody>
    </tbody>
  </table>
<div class="links">
     <a href="/books/new">Create new book</a><br>
</div>

<%= javascript_include_tag "book" %>
<%= javascript_include_tag "bookIndex" %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_for @book do |f| %>
      <div class="book-info">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %><br>
      </div>
      <div class="book-info">
      <%= f.label :author, "Author" %>
      <%= f.text_field :author%><br>
      </div>
      <div class="book-info">
      <%= f.label :year, "Year" %>
      <%= f.number_field :year, in:1950..2017 %><br>
      </div>
      <div class="book-info">
      <%= f.label :fiction, "Fiction" %>
      <%= f.check_box :fiction %><br>
      </div>
      <div id="book-info">
      <div class="book-info">
        <%= f.submit %>
      </div>
<% end %>

app/views/books/show.html.erb
<table class="book-table" id="book-info"></table>
<table id="reviews"></table>
<div id="my_review"></div>
<div class="links">
  <%= link_to("See reviews", book_reviews_path(@book), id: "show_reviews") %><br>
  <% if @isReviewed %><%= link_to("Write a review", new_book_review_path(@book), id: "write_review") %><br><% end %>
</div>
<p id="b_id" hidden=><%= @book.id %></p>
<div id="new_form" hidden>
  <% @review = Review.new %>
  <%= form_for @review, url: {action: "create"} do |f| %>
      <%= f.label :summary, "Summary: " %>
      <%= f.text_field :summary %><br>
      <%= f.label :rating, "Rating: " %>
      <%= f.number_field :rating, in:1..5 %><br>
      <%= f.label :body, "Body: " %>
      <%= f.text_area :body, size: "50x10" %><br>
      <%= f.submit %>
  <% end %>
</div>
<%= javascript_include_tag "bookShow" %>