config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/home'
  root 'welcome#home'

  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  
  get 'books/list', to: 'books#list', as: 'list_books'
  get 'book/detail/:id', to: 'books#detail', as: 'detail_book'
  resources :books do
    resources :reviews, only: [ :new, :create, :index, :show ]
    #get 'reviews', to: 'reviews#show', as: 'review'
    #get 'reviews/new', to: 'reviews#new'
    #post 'reviews', to: 'reviews#show'
  end
  
  #map.resources :books, has_many: :reviews
  
  resources :reviews, only: :destroy
  
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'user_edit'
  delete '/users/:id', to: 'users#destroy'
  patch '/users/:id', to: 'users#updateinfo'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolioProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    <%= yield %>
  </body>
  <div class="navbar">
    <% if user_signed_in? %>
      <ul>
      <li><%= link_to("Sign Out", destroy_user_session_path, :method => :delete) %></li>
      <li><%= link_to("My Page", user_path(current_user.id)) %></li>
      <li><%= link_to("Reviewed Books", books_path) %></li>
      </ul>
    <% else %>
      <ul>
      <li><%= link_to("Sign Up", new_user_registration_path) %></li>
      <li><%= link_to("Sign In", new_user_session_path) %></li>
      <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
      <li><%= link_to "Sign in with LinkedIn", user_linkedin_omniauth_authorize_path %></li>
      </ul>
    <% end %>
  </div>
</html>